language: python
python:
- "3.6"
- "3.4"
install: pip install tox-travis pylint

matrix:
  fast_finish: true
  include:
  - stage: test
    name: Unit tests
    script: tox
  - stage: lint
    name: Linting
    script: pylint
  allow_failures:
  - stage: lint
